security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: Email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\Auth0Authenticator
            logout:
                path: /logout
                target: /
            remember_me: false
            stateless: false

    access_control:
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/auth/callback, roles: PUBLIC_ACCESS } # ← C’est ESSENTIEL
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
